### ISSUE TITLE
Fix Internet Explorer and Safari formatting

### ISSUE THREAD

**Issue by hubyeti** [iltuzers/github-for-developers-7#2]
We need to fix the position of the photo in relation to the individual bio in both IE and Safari.

**Comment by iltuzers** [comment]
fixed bio in both IE and Safari,

**Comment by iltuzers** [comment]
![black-white-city](https://cloud.githubusercontent.com/assets/15082937/11325668/7d6ebc18-9121-11e5-884b-84c590f44691.jpg)
